version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - .postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build: ./
    container_name: fastapi_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    restart: always
